name: mogur
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  excel: ^4.0.3
  path_provider: ^2.1.2
  share_plus: ^10.0.0
  fl_chart: ^0.66.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_mogur.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_mogur.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFill